# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wind-simulation',
                'doc_host': 'https://GarethPaulBell.github.io',
                'git_url': 'https://github.com/GarethPaulBell/wind-simulation',
                'lib_path': 'wind_simulation'},
  'syms': {'wind_simulation.core': {'wind_simulation.core.foo': ('core.html#foo', 'wind_simulation/core.py')}}}
